# Generated by Django 3.2.16 on 2023-05-24 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230523_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'default_related_name': 'followings'},
        ),
    ]
